ME = 20190084

all : prob1 prob2 prob3

prob1: prob_1/prob_1.cpp
	g++ -o prob_1/$(ME)_prob_1.exe prob_1/prob_1.cpp

prob2: prob_2/prob_2.cpp
	g++ -o prob_2/$(ME)_prob_2.exe prob_2/prob_2.cpp

prob3: prob_3/prob_3.cpp
	g++ -o prob_3/$(ME)_prob_3.exe prob_3/prob_3.cpp
